import { currentCase, organization, mine } from './auth';
const currentYear = new Date().getFullYear();
export const queries: {table:string;filters:unknown[]}[]=[];
export let mode = 'populated';
export const setMode=(value:string)=>{mode=value;};
const sales=Array.from({length:2},(_,i)=>({id:`qa-sale-${i+1}`,sale_number:`QA-${i+1}`,sale_date:`${currentYear}-08-21`,quantity_oz:i?520:180,total_amount:i?1180000:405945,royalty_amount:i?35000:14059,status:i?'validated':'pending',seller_type:'mining_company',customers:{name:'Acheteur de test'},created_at:`${currentYear}-08-21`}));
function query(table:string, initial?:unknown) { const filters:unknown[]=[]; let single=false; let data=initial; let error:unknown=null;
 const response=()=> { if(mode==='error'&&['sales','gold_inventory'].includes(table))return {data:null,error:{message:'Source de test indisponible'}};
 if(data===undefined){if(table==='snp_organizations')data=single?organization():[organization()];else if(table==='mining_companies')data=single?mine():[mine()];else if(table==='snp_artisans_miniers')data=single?{id:'collector-test',nom:'Collecteur',prenoms:'de vérification',numero_carte:null}:[];else if(table==='sales'&&!currentCase().startsWith('mine'))data=mode==='empty'?[]:sales;else if(table==='daily_production'&&!currentCase().startsWith('mine'))data=mode==='empty'?[]:[2000,4100,2900,19300,15700,18500,20000,27000,12000].map((value,i)=>({production_date:`${currentYear}-${String(i+1).padStart(2,'0')}-01`,estimated_oz:value}));else data=single?null:[];}
 let result=data;if(Array.isArray(result)){for(const [method,column,value] of filters as string[][]){if(['gte','lte','eq'].includes(method)&&result[0]&&column in result[0])result=result.filter(row=>method==='gte'?row[column]>=value:method==='lte'?row[column]<=value:row[column]===value);}}
 queries.push({table,filters});return {data:result,error,count:Array.isArray(result)?result.length:0};};
 const chain:any=new Proxy(()=>{}, {get(_t,key){if(key==='then'){const p=Promise.resolve().then(response);return p.then.bind(p);}return (...args:unknown[])=>{if(key==='single'||key==='maybeSingle')single=true;if(['insert','update','delete','upsert'].includes(String(key)))throw Error('Écritures interdites dans le banc de vérification visuelle');filters.push([key,...args]);return chain;};},apply(){return chain;}});return chain; }
export const supabase={from:(table:string)=>query(table),rpc:(name:string)=>query(name,name==='snp_current_organization_id'?organization().id:name==='snp_current_collector_id'?'collector-test':name==='snp_dgi_charger_tableau_collecte'?{has_data:false,summary:{},monthly:[],tax_breakdown:[],contributors:[],priorities:[]}:name==='snp_dgmg_charger_tableau_reglementaire'?{has_data:false,summary:{},monthly:[],compliance:{},activities:[],attention:{},filter_options:{}}:name==='snp_situation_societe'?{}:[]),auth:{getSession:async()=>({data:{session:null}}),getUser:async()=>({data:{user:null}})},storage:{from:()=>({createSignedUrl:async()=>({data:null,error:{message:'Pas de logo de test'}})})},functions:{invoke:async()=>({data:[],error:null})}};
