export const internationalSalesCopy = {
  fr: {
    title: 'Ventes d’or à l’international', subtitle: 'Consultez et suivez toutes les ventes d’or exportées et leur état de règlement.',
    sales: 'Ventes d’or', allSales: 'Toutes les ventes', export: 'Exporter', newSale: 'Nouvelle vente',
    all: 'Toutes', unpaid: 'En attente de paiement', partial: 'Partiellement payées', paid: 'Payées', disputed: 'Litige', cancelled: 'Annulées',
    approval: 'En validation', rejected: 'Refusées', unconfirmed: 'À vérifier',
    singular: { all: 'Toutes', unpaid: 'En attente de paiement', partial: 'Partiellement payée', paid: 'Payée', disputed: 'Litige', cancelled: 'Annulée', approval: 'En validation', rejected: 'Refusée', unconfirmed: 'À vérifier' },
    search: 'Rechercher (référence, client, mine…)', searchLabel: 'Rechercher une vente', status: 'Statut', allOptions: 'Tous',
    shippingDate: 'Date d’expédition', from: 'Date d’expédition : début', to: 'Date d’expédition : fin',
    client: 'Client', company: 'Mine / Comptoir', filters: 'Filtres', reset: 'Réinitialiser', currency: 'Devise', workflow: 'Étape de la vente',
    reference: 'Référence vente', invoice: 'Facture', quantity: 'Quantité', grams: 'grammes', price: 'Prix au gramme', total: 'Montant total', paidAmount: 'Montant payé', actions: 'Actions',
    license: 'Licence exp.', noLicense: 'Licence non renseignée', noInvoice: 'Facture non renseignée',
    noCustomer: 'Client non renseigné', noCompany: 'Structure non renseignée', noCountry: 'Pays non renseigné', noShipment: 'Non renseignée',
    details: 'Voir la vente', more: 'Autres actions', newTab: 'Ouvrir dans un nouvel onglet', copy: 'Copier la référence', copied: 'Référence copiée.',
    copyError: 'Impossible de copier la référence.', retry: 'Réessayer', loading: 'Chargement des ventes…',
    loadError: 'Le registre des ventes n’a pas pu être chargé. Réessayez pour consulter des données à jour.',
    exportError: 'L’export n’a pas pu être généré. Veuillez réessayer.',
    empty: 'Aucune vente à afficher', emptyHint: 'Aucune vente disponible dans votre périmètre.',
    noResults: 'Aucune vente ne correspond aux filtres', noResultsHint: 'Modifiez vos critères ou réinitialisez les filtres.',
    invalidDates: 'La date de fin doit être postérieure ou égale à la date de début.',
    range: 'Affichage de', on: 'sur', row: 'vente', rows: 'ventes', perPage: '/ page', pageSize: 'Ventes par page', previous: 'Page précédente', next: 'Page suivante', page: 'Page',
    paymentHint: 'Encaissements réels approuvés, dans la devise de la vente. Les engagements virtuels sont exclus.',
    unknownPayment: 'Encaissement à vérifier', percentage: 'Pourcentage réglé',
    statuses: { create_sales: 'Brouillon', pending_management_approval: 'Validation SONASP attendue', management_approved: 'Validée par la SONASP',
      pending_for_customer_approval: 'Accord client attendu', customer_approved: 'Acceptée par le client', waiting_for_payment: 'Paiement attendu',
      virtual_payment: 'Engagement / règlement à confirmer', payment_received: 'Règlement confirmé', completed: 'Vente clôturée',
      management_rejected: 'Refusée par la SONASP', customer_rejected: 'Refusée par le client' } as Record<string, string>,
  },
  en: {
    title: 'International gold sales', subtitle: 'Browse exported gold sales and track their settlement status.',
    sales: 'Gold sales', allSales: 'All sales', export: 'Export', newSale: 'New sale',
    all: 'All', unpaid: 'Awaiting payment', partial: 'Partially paid', paid: 'Paid', disputed: 'Disputed', cancelled: 'Cancelled',
    approval: 'Under approval', rejected: 'Rejected', unconfirmed: 'To verify',
    singular: { all: 'All', unpaid: 'Awaiting payment', partial: 'Partially paid', paid: 'Paid', disputed: 'Disputed', cancelled: 'Cancelled', approval: 'Under approval', rejected: 'Rejected', unconfirmed: 'To verify' },
    search: 'Search (reference, customer, mine…)', searchLabel: 'Search sales', status: 'Status', allOptions: 'All',
    shippingDate: 'Shipment date', from: 'Shipment date: start', to: 'Shipment date: end',
    client: 'Customer', company: 'Mine / Trading office', filters: 'Filters', reset: 'Reset filters', currency: 'Currency', workflow: 'Sale workflow',
    reference: 'Sale reference', invoice: 'Invoice', quantity: 'Quantity', grams: 'grams', price: 'Price per gram', total: 'Total amount', paidAmount: 'Amount paid', actions: 'Actions',
    license: 'Export licence', noLicense: 'Licence not provided', noInvoice: 'Invoice not provided',
    noCustomer: 'Customer not provided', noCompany: 'Organisation not provided', noCountry: 'Country not provided', noShipment: 'Not provided',
    details: 'View sale', more: 'More actions', newTab: 'Open in a new tab', copy: 'Copy reference', copied: 'Reference copied.',
    copyError: 'Unable to copy the reference.', retry: 'Retry', loading: 'Loading sales…',
    loadError: 'Unable to load the sales register. Retry to view up-to-date data.', exportError: 'Unable to generate the export. Please retry.',
    empty: 'No sales to display', emptyHint: 'No sales are available within your access scope.',
    noResults: 'No sales match your filters', noResultsHint: 'Change your search criteria or reset the filters.',
    invalidDates: 'The end date must be on or after the start date.', range: 'Showing', on: 'of', row: 'sale', rows: 'sales', perPage: '/ page',
    pageSize: 'Sales per page', previous: 'Previous page', next: 'Next page', page: 'Page',
    paymentHint: 'Approved actual receipts in the sale currency. Virtual commitments are excluded.', unknownPayment: 'Receipt to verify', percentage: 'Percentage paid',
    statuses: { create_sales: 'Draft', pending_management_approval: 'Awaiting SONASP approval', management_approved: 'Approved by SONASP',
      pending_for_customer_approval: 'Awaiting customer approval', customer_approved: 'Accepted by customer', waiting_for_payment: 'Awaiting payment',
      virtual_payment: 'Commitment / settlement to confirm', payment_received: 'Settlement confirmed', completed: 'Sale closed',
      management_rejected: 'Rejected by SONASP', customer_rejected: 'Rejected by customer' } as Record<string, string>,
  },
};
